"use client"

import {
  Sparkles,
  Shield,
  TrendingUp,
  Zap,
  Star,
  Heart,
  Check,
  Rocket,
  Target,
  Users,
  Clock,
  Award,
  BarChart3,
  Bell,
  Cloud,
  Code,
  Cpu,
  Database,
  Fingerprint,
  Gift,
  Globe,
  Headphones,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  MessageSquare,
  Moon,
  Phone,
  PieChart,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  ShoppingBag,
  Smile,
  ThumbsUp,
  Trophy,
  Umbrella,
  Upload,
  Video,
  Wifi,
  type LucideIcon,
} from "lucide-react"

const map: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  shield: Shield,
  "trending-up": TrendingUp,
  zap: Zap,
  star: Star,
  heart: Heart,
  check: Check,
  rocket: Rocket,
  target: Target,
  users: Users,
  clock: Clock,
  award: Award,
  "bar-chart": BarChart3,
  bell: Bell,
  cloud: Cloud,
  code: Code,
  cpu: Cpu,
  database: Database,
  fingerprint: Fingerprint,
  gift: Gift,
  globe: Globe,
  headphones: Headphones,
  layers: Layers,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  "message-square": MessageSquare,
  moon: Moon,
  phone: Phone,
  "pie-chart": PieChart,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share: Share2,
  "shopping-bag": ShoppingBag,
  smile: Smile,
  "thumbs-up": ThumbsUp,
  trophy: Trophy,
  umbrella: Umbrella,
  upload: Upload,
  video: Video,
  wifi: Wifi,
}

/** Resolve a lucide icon by name. Falls back to Sparkles. */
export function pickIcon(name: string): LucideIcon {
  return map[name] ?? Sparkles
}

export const iconNames: string[] = Object.keys(map)
